import GapEntropy.UniversalStagePrefix
import Mathlib.Probability.Process.Filtration

/-!
# The actual call-history filtration

The sigma algebra at call r is generated by the seed, the actual row boundary,
and all reward rows strictly before that boundary. It is increasing, contains
the actual controller state, and every one of its events has the exact prefix
representation required by the stopped-block Gaussian theorem.
-/
noncomputable section
open MeasureTheory
open scoped Classical
namespace GapEntropy.UniversalAttempt
open FiniteCallProgram
variable {n : ℕ}

abbrev StoppedData (n : ℕ) := Seed × ℕ × Values n

def maskedRows (t : ℕ) (x : Values n) : Values n := extendBlock t (firstBlock t x)

@[simp] theorem maskedRows_apply (t : ℕ) (x : Values n) (s : ℕ) :
    maskedRows t x s = if s < t then x s else fun _ => 0 := by
  unfold maskedRows extendBlock firstBlock
  split_ifs <;> rfl

theorem maskedRows_eq (t : ℕ) (x : Values n) (s : ℕ) (hs : s < t) :
    maskedRows t x s = x s := by simp only [maskedRows_apply, if_pos hs]

theorem maskedRows_maskedRows (s t : ℕ) (hst : s ≤ t) (x : Values n) :
    maskedRows s (maskedRows t x) = maskedRows s x := by
  funext i
  by_cases hi : i < s
  · simp [maskedRows_apply, hi, hi.trans_le hst]
  · simp [maskedRows_apply, hi]

theorem measurable_maskedRows : Measurable (fun p : ℕ × Values n => maskedRows p.1 p.2) := by
  apply measurable_from_prod_countable_right
  intro t
  exact (extendBlock_measurable t).comp (firstBlock_measurable t)

theorem stage_boundary_mono (c : Config) (x : Values n) :
    Monotone (fun r => boundary (stage c x r)) := by
  apply monotone_nat_of_le_succ
  intro r
  simpa only [stage, boundary_stageStep] using boundary_le_nextBoundary c (stage c x r)

def stoppedData (c : Config) (r : ℕ) (ω : SampleSpace n) : StoppedData n :=
  let t := boundary (stage c ω.2 r)
  (ω.1, t, maskedRows t ω.2)

def reconstructPast (c : Config) (r : ℕ) (p : StoppedData n) : StoppedData n :=
  let t := boundary (stage c p.2.2 r)
  (p.1, t, maskedRows t p.2.2)

theorem measurable_stoppedData (c : Config) (r : ℕ) : Measurable (stoppedData c (n := n) r) :=
  measurable_fst.prodMk ((measurable_stage_boundary c r).prodMk
    (measurable_maskedRows.comp ((measurable_stage_boundary c r).prodMk measurable_snd)))

theorem measurable_reconstructPast (c : Config) (r : ℕ) : Measurable (reconstructPast c (n := n) r) := by
  have ht : Measurable (fun p : StoppedData n => boundary (stage c p.2.2 r)) :=
    measurable_boundary.comp ((measurable_stage c r).comp measurable_snd.snd)
  exact measurable_fst.prodMk (ht.prodMk (measurable_maskedRows.comp (ht.prodMk measurable_snd.snd)))

theorem stage_eq_from_later_stoppedData (c : Config) (r s : ℕ) (hrs : r ≤ s)
    (ω : SampleSpace n) : stage c ω.2 r = stage c (stoppedData c s ω).2.2 r := by
  exact (stage_prefix_local c r (boundary (stage c ω.2 s)) ω.2
    (maskedRows (boundary (stage c ω.2 s)) ω.2)
    (fun i hi => (maskedRows_eq _ _ i hi).symm)).2 (stage_boundary_mono c ω.2 hrs)

theorem stoppedData_reconstruct (c : Config) (r s : ℕ) (hrs : r ≤ s) :
    stoppedData c (n := n) r = reconstructPast c r ∘ stoppedData c s := by
  funext ω
  have he := stage_eq_from_later_stoppedData c r s hrs ω
  change (_, boundary (stage c ω.2 r), maskedRows (boundary (stage c ω.2 r)) ω.2) =
    (_, boundary (stage c (stoppedData c s ω).2.2 r),
      maskedRows (boundary (stage c (stoppedData c s ω).2.2 r)) (stoppedData c s ω).2.2)
  rw [← he]
  have hm := maskedRows_maskedRows _ _ (stage_boundary_mono c ω.2 hrs) ω.2
  exact congrArg (fun x => (ω.1, boundary (stage c ω.2 r), x)) hm.symm

@[instance_reducible] def callPast (c : Config) (r : ℕ) : MeasurableSpace (SampleSpace n) :=
  MeasurableSpace.comap (stoppedData c r) inferInstance

theorem callPast_mono (c : Config) : Monotone (callPast c (n := n)) := by
  intro r s hrs
  exact MeasurableSpace.comap_le_comap_of_eq_comp (reconstructPast c r)
    (measurable_reconstructPast c r) (stoppedData_reconstruct c r s hrs)

def callFiltration (c : Config) : Filtration ℕ (inferInstance : MeasurableSpace (SampleSpace n)) where
  seq := callPast c
  mono' := callPast_mono c
  le' r := (measurable_stoppedData c r).comap_le

theorem stage_adapted (c : Config) (r : ℕ) :
    Measurable[callPast c r] (fun ω : SampleSpace n => stage c ω.2 r) := by
  have hm : Measurable (fun p : StoppedData n => stage c p.2.2 r) :=
    (measurable_stage c r).comp measurable_snd.snd
  have he : (fun ω : SampleSpace n => stage c ω.2 r) =
      (fun p : StoppedData n => stage c p.2.2 r) ∘ stoppedData c r := by
    funext ω
    exact stage_eq_from_later_stoppedData c r r le_rfl ω
  rw [he]
  exact hm.comp (comap_measurable (stoppedData c r))

def dataFromPrefix (t : ℕ) (p : SeedPrefix n t) : StoppedData n :=
  (p.1, t, extendBlock t p.2)

theorem measurable_dataFromPrefix (t : ℕ) : Measurable (dataFromPrefix (n := n) t) :=
  measurable_fst.prodMk (measurable_const.prodMk ((extendBlock_measurable t).comp measurable_snd))

theorem stoppedData_eq_at_boundary (c : Config) (r t : ℕ) (ω : SampleSpace n)
    (ht : boundary (stage c ω.2 r) = t) :
    stoppedData c r ω = dataFromPrefix t (seedPrefix t ω) := by
  unfold stoppedData
  rw [ht]
  rfl

/-- Every actual past event has the stopped-prefix factorization needed by
`GaussianBlocks.measure_event_stoppedBlock`, including events recording all
previous flags, not merely the current finite active set. -/
theorem past_event_prefix (c : Config) (r t : ℕ) (R : Set (SampleSpace n))
    (hR : MeasurableSet[callPast c r] R) :
    ∃ E : Set (SeedPrefix n t), MeasurableSet E ∧
      {ω | boundary (stage c ω.2 r) = t ∧ ω ∈ R} = (seedPrefix t) ⁻¹' E := by
  obtain ⟨A, hA, hpre⟩ := MeasurableSpace.measurableSet_comap.mp hR
  obtain ⟨B, hB, hb⟩ := boundary_prefix c r t
  refine ⟨B ∩ (dataFromPrefix t) ⁻¹' A,
    hB.inter ((measurable_dataFromPrefix t) hA), ?_⟩
  ext ω
  constructor
  · rintro ⟨ht, hω⟩
    refine ⟨?_, ?_⟩
    · change ω ∈ (seedPrefix t) ⁻¹' B
      rw [← hb]
      exact ht
    · have hm : stoppedData c r ω ∈ A := by rw [← hpre] at hω; exact hω
      rwa [stoppedData_eq_at_boundary c r t ω ht] at hm
  · rintro ⟨ht, hω⟩
    have ht' : boundary (stage c ω.2 r) = t := by
      change ω ∈ (seedPrefix t) ⁻¹' B at ht
      rw [← hb] at ht
      exact ht
    refine ⟨ht', ?_⟩
    rw [← hpre]
    change stoppedData c r ω ∈ A
    rwa [stoppedData_eq_at_boundary c r t ω ht']

/-- Restrict a longer seed/reward prefix to a shorter one. -/
def restrictSeedPrefix (t T : ℕ) (ht : t ≤ T) (p : SeedPrefix n T) : SeedPrefix n t :=
  (p.1, fun i => p.2 ⟨i, i.isLt.trans_le ht⟩)

theorem measurable_restrictSeedPrefix (t T : ℕ) (ht : t ≤ T) :
    Measurable (restrictSeedPrefix (n := n) t T ht) := by
  exact measurable_fst.prodMk (measurable_pi_lambda _ (fun i =>
    (measurable_pi_apply _).comp measurable_snd))

/-- A measurable parameter branch can move the prefix representation forward
to a deterministic offset, for example past the entry PAC/reference block and
up to the start of its fresh active-arm estimates. -/
theorem past_event_choice_prefix {κ : Type*} [MeasurableSpace κ] [MeasurableSingletonClass κ]
    (c : Config) (r : ℕ) (choice : SampleSpace n → κ)
    (hchoice : Measurable[callPast c r] choice) (q : κ) (t T : ℕ) (htT : t ≤ T)
    (hboundary : ∀ ω, choice ω = q → boundary (stage c ω.2 r) = t)
    (R : Set (SampleSpace n)) (hR : MeasurableSet[callPast c r] R) :
    ∃ E : Set (SeedPrefix n T), MeasurableSet E ∧
      {ω | ω ∈ R ∧ choice ω = q} = (seedPrefix T) ⁻¹' E := by
  let A := R ∩ choice ⁻¹' {q}
  have hA : MeasurableSet[callPast c r] A := hR.inter (hchoice (measurableSet_singleton q))
  obtain ⟨E, hE, he⟩ := past_event_prefix c r t A hA
  refine ⟨(restrictSeedPrefix t T htT) ⁻¹' E,
    (measurable_restrictSeedPrefix t T htT) hE, ?_⟩
  have hevent : {ω | boundary (stage c ω.2 r) = t ∧ ω ∈ A} =
      {ω | ω ∈ R ∧ choice ω = q} := by
    ext ω
    constructor
    · rintro ⟨_, hR, hq⟩
      exact ⟨hR, hq⟩
    · rintro ⟨hR, hq⟩
      exact ⟨hboundary ω hq, hR, hq⟩
  rw [← hevent, he]
  rfl

end GapEntropy.UniversalAttempt
